apiVersion: modelops/v1
kind: Workspace
metadata:
  name: medmem-workspace
spec:
  scheduler:
    replicas: 1
    image: ghcr.io/institutefordiseasemodeling/modelops-dask-scheduler:latest
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
  workers:
    # Keep concurrency reasonable (2 worker procs per pod) so each proc
    # has ~6 GiB when aggregation spikes.
    replicas: 6
    image: ghcr.io/institutefordiseasemodeling/modelops-dask-worker:latest
    processes: 2
    threads: 1
    resources:
      requests:
        cpu: "4"
        memory: "12Gi"
      limits:
        cpu: "4"
        memory: "12Gi"
  autoscaling:
    enabled: true
    min_workers: 4
    max_workers: 12
    target_cpu: 70
